apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: sthallys/api-conversao:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: conversao-service
spec:
  selector:
    app: conversao
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
